# Tensor Creation

**torch.tensor()**: Creates a tensor from a Python list or NumPy array.

In [1]:
import torch
data = [[1, 2], [3, 4]]
tensor = torch.tensor(data)
tensor


tensor([[1, 2],
        [3, 4]])

**torch.zeros()**: Creates a tensor filled with zeros.

In [2]:
zeros_tensor = torch.zeros((2, 3))
zeros_tensor


tensor([[0., 0., 0.],
        [0., 0., 0.]])

**torch.ones()**: Creates a tensor filled with ones.

In [3]:
ones_tensor = torch.ones((2, 3))
ones_tensor


tensor([[1., 1., 1.],
        [1., 1., 1.]])

**torch.rand()**: Creates a tensor with random values.

In [4]:
rand_tensor = torch.rand((2, 3))
rand_tensor


tensor([[0.1410, 0.3095, 0.7251],
        [0.8776, 0.2127, 0.6840]])

**torch.randn()**: Creates a tensor with random values from a normal distribution.

In [5]:
randn_tensor = torch.randn((2, 3))
randn_tensor


tensor([[ 1.4036,  0.5928, -1.7883],
        [ 0.5948, -0.1342, -1.3288]])

# Tensor Operations

**torch.add()**: Element-wise addition of two tensors.

In [6]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
result = torch.add(a, b)
result


tensor([5, 7, 9])

**torch.sub()**: Element-wise subtraction of two tensors.

In [7]:
result = torch.sub(a, b)
result


tensor([-3, -3, -3])

**torch.mul()**: Element-wise multiplication of two tensors.

In [8]:
result = torch.mul(a, b)
result


tensor([ 4, 10, 18])

**torch.div()**: Element-wise division of two tensors.

In [9]:
result = torch.div(a, b)
result


tensor([0.2500, 0.4000, 0.5000])

**torch.matmul()**: Matrix product of two tensors.

In [10]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
result = torch.matmul(a, b)
result


tensor([[19, 22],
        [43, 50]])

**torch.sum()**: Computes the sum of elements in a tensor.

In [11]:
result = torch.sum(a)
result


tensor(10)

**torch.mean()**: Computes the mean of all elements in a tensor.

In [12]:
result = torch.mean(a.float())
result


tensor(2.5000)

**torch.max()**: Computes the maximum value in a tensor.

In [13]:
result = torch.max(a)
result


tensor(4)

**torch.min()**: Computes the minimum value in a tensor.

In [14]:
result = torch.min(a)
result


tensor(1)

# Autograd



**torch.autograd.grad()**: Computes the gradient of a tensor.

In [15]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2
y.backward()
x.grad


tensor(4.)

# Neural Networks

**torch.nn.Module:** Base class for all neural network modules.

In [18]:
import torch.nn as nn
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.linear = nn.Linear(2, 1)
    
    def forward(self, x):
        return self.linear(x)


**torch.nn.Sequential:** A sequential container.

In [19]:
model = nn.Sequential(
    nn.Linear(2, 2),
    nn.ReLU(),
    nn.Linear(2, 1)
)

**torch.nn.Conv2d:** Applies a 2D convolution.

In [20]:
conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3)

**torch.nn.ReLU:** Applies the ReLU activation function.

In [21]:
relu = nn.ReLU()

**torch.nn.Sigmoid:** Applies the Sigmoid activation function.

In [22]:
sigmoid = nn.Sigmoid()

# Optimization


**torch.optim.SGD:** Stochastic gradient descent optimizer.

In [23]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

**torch.optim.Adam:** Adam optimizer.

In [24]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

**torch.optim.lr_scheduler:** Learning rate scheduler.

In [25]:
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1, gamma=0.9)

# Data Loading


**torch.utils.data.DataLoader:** Loads data from a dataset.

In [26]:
from torch.utils.data import DataLoader, TensorDataset
dataset = TensorDataset(torch.tensor([[1, 2], [3, 4]]), torch.tensor([1, 0]))
dataloader = DataLoader(dataset, batch_size=2)

# Saving and Loading

**torch.save():** Saves a model or tensor.

In [27]:
torch.save(model.state_dict(), 'model.pth')

**torch.load():** Loads a saved model or tensor.

In [28]:
model.load_state_dict(torch.load('model.pth'))

<All keys matched successfully>

# Utilities

**torch.device:** Specifies the device for a tensor.

In [29]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor = torch.tensor([1, 2, 3]).to(device)

**torch.cuda.is_available():** Checks if CUDA device is available.

In [30]:
is_cuda_available = torch.cuda.is_available()
print(is_cuda_available)

False


**torch.backends.cudnn.enabled:** Enables/disables CUDNN acceleration.

In [31]:
torch.backends.cudnn.enabled = True